title: CodeNinja
email: your-email@example.com
description: Основы и нюансы самостоятельной разработки сайтов.
baseurl: "/CodeNinja"
url: "https://webzwezda.github.io"


encoding: utf-8
highlighter: rouge


paginate: 7

permalink: /:categories/:title.html
