title: Как создать сайт?
email: your-email@example.com
description: Основы и нюансы самостоятельной разработки сайтов.
baseurl: "/CodeNindzya"
url: ""


encoding: utf-8
highlighter: rouge


paginate: 7

permalink: /:categories/:title.html
